# Generated by Django 6.0.4 on 2026-04-24 06:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TIMBRE1', 'Timbre Principal'), ('TIMBRE2', 'Timbre Secundario'), ('ESP32', 'ESP32'), ('CONTROLADOR', 'Controlador Central')], default='ESP32', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_dispositivo', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('configuracion_json', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Estado del Dispositivo',
                'verbose_name_plural': 'Estados de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='EventoHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('RECREO', 'Recreo'), ('CAMBIO_CLASE', 'Cambio de Clase'), ('ALMUERZO', 'Almuerzo'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evento de Horario',
                'verbose_name_plural': 'Eventos de Horario',
                'ordering': ['horario_escolar', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEscolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('COMPLETA', 'Jornada Completa')], default='MANANA', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario Escolar',
                'verbose_name_plural': 'Horarios Escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la institución')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('voltaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memoria_libre', models.BigIntegerField(blank=True, null=True)),
                ('uptime', models.BigIntegerField(blank=True, null=True)),
                ('wifi_signal', models.IntegerField(blank=True, null=True)),
                ('estado_detallado', models.JSONField(default=dict)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='timbre.dispositivo')),
            ],
            options={
                'verbose_name': 'Diagnóstico de Dispositivo',
                'verbose_name_plural': 'Diagnósticos de Dispositivos',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comando', models.CharField(choices=[('TEST', 'Prueba'), ('REINICIAR', 'Reiniciar'), ('ACTUALIZAR_CONFIG', 'Actualizar Configuración'), ('TIMBRE_MANUAL', 'Activar Timbre Manual'), ('SILENCIAR', 'Silenciar'), ('ACTUALIZAR_FIRMWARE', 'Actualizar Firmware')], max_length=30)),
                ('parametros', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido por dispositivo'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='timbre.dispositivo')),
            ],
            options={
                'verbose_name': 'Comando Remoto',
                'verbose_name_plural': 'Comandos Remotos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='timbre.estadodispositivo'),
        ),
        migrations.CreateModel(
            name='ActivacionTimbre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado al dispositivo'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('comando_enviado', models.JSONField(default=dict)),
                ('respuesta', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activaciones', to='timbre.dispositivo')),
                ('evento_horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activaciones', to='timbre.eventohorario')),
            ],
            options={
                'verbose_name': 'Activación de Timbre',
                'verbose_name_plural': 'Activaciones de Timbre',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.AddField(
            model_name='eventohorario',
            name='horario_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='timbre.horarioescolar'),
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_respuesta', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(default=dict)),
                ('tiempo_procesamiento_ms', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comando', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='timbre.comandoremoto')),
            ],
            options={
                'verbose_name': 'Respuesta de Comando',
                'verbose_name_plural': 'Respuestas de Comandos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la sede')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de sede')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='timbre.institucion')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['institucion', 'nombre'],
                'unique_together': {('institucion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='horarioescolar',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_escolares', to='timbre.sede'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='timbre.sede'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='timbre_usuario_groups', to='auth.group')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='timbre.institucion')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='timbre.sede')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='timbre_usuario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('TIMBRE', 'Activación de Timbre'), ('DISPOSITIVO', 'Estado de Dispositivo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='timbre.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='timbre.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='comandoremoto',
            name='usuario_emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_enviados', to='timbre.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='timbre.rol')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='timbre.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='timbre.usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'unique_together': {('usuario', 'rol', 'sede')},
            },
        ),
    ]
